### ISSUE TITLE
Not Working for Some Courses (Introduction to D3)

### ISSUE THREAD

**Issue by hemratna** [markbrown4/egghead-downloader#2]
Hi @markbrown4 ,

Thanks a lot for such a wonderful script.

But I am getting some error like below.

`id = contentUrl.match(regex)[1];` inside /download.coffee:27

I am trying to download from [Introduction to D3](https://egghead.io/courses/introduction-to-d3)

Kindly guide me how to resolve this issue.

Regards,

**Comment by markbrown4** [comment]
Hi Hemratna,

I suspect the error may be due to trying to download pro videos without a pro account?

> This lesson is for PRO members.

I'll modify the script to print an error if it can't find the download link and keep working through the list of files.  Let me know if you do have a pro account and have added your email / pass to `.env` though, I can test that flow.

**Comment by hemratna** [comment]
Hi @markbrown4 
I have PRO account.
And I was able to download some other series.
I will pull the updated code and try once again.

Once again, Thank you very much for this script.
Regards, :)

**Comment by markbrown4** [comment]
Would you be able to give this another try?

I've fixed an odd case of some pages not having a contentURL meta.

**Comment by pingshunhuangalex** [comment]
Hi @markbrown4 

I got the same issue with PRO account. I can only download the free part of the D3 v4 class, while the remaining files just threw me `This lesson is for PRO members.` error. Could you please have another look at it. Thanks.
